### ISSUE TITLE
Monolog email handler

### ISSUE THREAD

**Issue by ahmedmhmd** [lexik/LexikMaintenanceBundle#21]
When using bundle with Monolog email handler at logging level: critical 

This will cause the mail to flood with invalid error messages about uncaught exception

How about adding an option to render the twig file rather than throwing the exception? (optionally)

**Comment by krewetka** [comment]
:+1:  for that

I searched for a way to turn this off but found Monolog solution for 404 only, not for 503

http://symfony.com/doc/current/cookbook/logging/monolog_regex_based_excludes.html
