### ISSUE TITLE
LexikMaintenance ( 2.0.x ) not compatible with symfony 2.5.11

### ISSUE THREAD

**Issue by huitiemesens** [lexik/LexikMaintenanceBundle#43]
there is an issue with lexikMaintenance dependecies : symfony/dependency-injection: ~2.7 is not compatible with symfony 2.5.11 and above .

**Comment by cedric-g** [comment]
Hi, yes the master branch (and so the 2.0.x alias) requires Symfony 2.7. We don't support anymore previous versions.
